version: '3.8'

services:
  mysql_db:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: "Raghu123@"
      MYSQL_DATABASE: "nutrisip"
      MYSQL_USER: "nutrisip"
      MYSQL_PASSWORD: "nutrisip"
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "5000:5000"
    environment:
      MYSQL_HOST: mysql_db
      MYSQL_USER: nutrisip
      MYSQL_PASSWORD: nutrisip
      MYSQL_DATABASE: nutrisip
    depends_on:
      mysql_db:
        condition: service_healthy

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "80:3000"
    depends_on:
      - backend
    environment:
      REACT_APP_BACKEND_URL: http://backend:5000
      REACT_APP_WEBSOCKET_URL: ws://backend:5000

volumes:
  mysql_data:
